version: '3.7'
services: 
    eureka-server:
        image: eureka-server
        ports: 
            - "8761:8761"
        networks: 
            - app-network
    
    

networks: 
    app-network:
        
