
version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:885843804602:task-definition/sahil-intcde041-coupon-service-lb:1"
        LoadBalancerInfo:
          ContainerName: "coupon-service"
          ContainerPort: "5200"
        PlatformVersion: "LATEST"